name: Deploy to IBM Code Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install IBM Cloud CLI
        run: |
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
          ibmcloud --version

      - name: Debug API Key Presence
        env:
          IBMCLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
        run: |
          if [[ -z "$IBMCLOUD_API_KEY" ]]; then
            echo "❌ ERROR: IBM_CLOUD_API_KEY is empty!"
            exit 1
          else
            echo "✅ IBM_CLOUD_API_KEY is set."
          fi

      - name: Authenticate with IBM Cloud
        env:
          IBMCLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
        run: |
          echo "$IBMCLOUD_API_KEY" | ibmcloud login --apikey @- -r us-east
