name: Deploy to IBM Cloud Code Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install IBM Cloud CLI
        run: |
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
          ibmcloud --version

      - name: Authenticate with IBM Cloud
        env:
          IBMCLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
        run: |
          # Directly pass the API key instead of piping it
          ibmcloud login --apikey "$IBMCLOUD_API_KEY" -r us-east
          
      - name: Target Resource Group
        run: |
          ibmcloud target -g Default
          # Replace "Default" with your actual resource group name if needed

      - name: Install IBM Cloud Code Engine Plugin
        run: |
          ibmcloud plugin install code-engine

      - name: Build Docker Image
        run: |
          docker build -t cyberdarl/jiggy:latest .

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker Image to Docker Hub
        run: |
          docker push cyberdarl/jiggy:latest

      - name: Deploy to IBM Cloud Code Engine
        run: |
          ibmcloud ce project select --name cool
          ibmcloud ce app deploy --name cool-sito --image cyberdarl/jiggy:latest --region us-east
