name: Deploy to IBM Cloud Code Engine

on:
  push:
    branches:
      - main  # Change if your branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use a runner with Linux support
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install IBM Cloud CLI
        run: |
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
          ibmcloud --version  # Verify installation

      - name: Authenticate with IBM Cloud
        run: |
          echo "${{ secrets.IBM_CLOUD_API_KEY }}" | ibmcloud login --apikey @- -r us-east

      - name: Target IBM Cloud Container Registry
        run: |
          ibmcloud cr region-set us-east
          ibmcloud cr login

      - name: Deploy to Code Engine
        run: |
          ibmcloud ce project select --name medical-app
          ibmcloud ce application apply --name my-app --image my-docker-image:latest
