name: Deploy to IBM Cloud Code Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install IBM Cloud CLI
        run: |
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
          ibmcloud --version  # Verify installation

      - name: Login to IBM Cloud
        env:
          IBMCLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
        run: |
          echo ${IBMCLOUD_API_KEY} | ibmcloud login --apikey @- -r us-east
          ibmcloud target --cf
          
      - name: Push Docker image to IBM Cloud Container Registry
        run: |
          docker build -t us.icr.io/your-registry-name/your-image-name:latest .
          echo "${{ secrets.IBM_CLOUD_API_KEY }}" | docker login --username iamapikey --password-stdin us.icr.io
          docker push us.icr.io/your-registry-name/your-image-name:latest

      - name: Deploy to IBM Cloud Code Engine
        run: |
          ibmcloud code-engine app deploy --name your-app-name --image us.icr.io/your-registry-name/your-image-name:latest --region us-east

