jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install IBM Cloud CLI
        run: |
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
          ibmcloud --version  # Verify installation

      - name: Install IBM Cloud Code Engine Plugin
        run: |
          ibmcloud plugin install code-engine
          ibmcloud ce --help  # Verify installation

      - name: Authenticate with IBM Cloud
        run: echo "${{ secrets.IBM_CLOUD_API_KEY }}" | ibmcloud login --apikey @- -r us-east

      - name: Set target project
        run: ibmcloud ce project select -n medical-app

      - name: Deploy application
        run: ibmcloud ce app deploy --name medical-app --image us.icr.io/your-namespace/your-app-image:latest
